#define FNAME_LENGTH 30
#define LNAME_LENGTH 30
#define BDAY_LENGTH 9
#define GENDER_LENGTH 2
#define FAVCOLOR_LENGTH 15
#define CHAR_HOLDER_VALUE_LENGTH 30
#define MAX_USERS 100
#define MAX_USERS_ROW 10
#define MAX_USER_COL 10

#define USER_START_TAG "<user>"
#define USER_END_TAG "</user>"
#define ID_START_TAG "<id>"
#define ID_END_TAG "</id>"
#define FIRST_NAME_START_TAG "<firstName>"
#define FIRST_NAME_END_TAG "</firstName>"
#define LAST_NAME_START_TAG "<lastName>"
#define LAST_NAME_END_TAG "</lastName>"
#define BDAY_START_TAG "<birthday>"
#define BDAY_END_TAG "</birthday>"
#define GENDER_START_TAG "<gender>"
#define GENDER_END_TAG "</gender>"
#define FAVCOLOR_START_TAG "<favColor>"
#define FAVCOLOR_END_TAG "</favColor>"
#define AGE_START_TAG "<age>"
#define AGE_END_TAG "</age>"

#define USER_BINARY_FILE_START_TAG "$u$3r*"
#define USER_BINARY_FILE_END_TAG  "#u$3r*